# **Tarea Numpy**

In [ ]:
#Crea un arreglo de 10 cincos.
import numpy as np
lista = [5,5,5,5,5,5,5,5,5,5]
arreglo = np.array(lista)

print(arreglo)


[5 5 5 5 5 5 5 5 5 5]


In [ ]:
#Crea un arreglo de enteros pares desde 10, inclusive, hasta 50, inclusive.
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
#Crea una matriz cuadrada de 4 por 4 de números enteros aleatorios.
import numpy.random as ra

matriz_aleatorio=np.random.randint(0,100, size=(4,4))
print(matriz_aleatorio)

[[37 66 47 15]
 [59 63 44 13]
 [10 86  1 54]
 [ 6 85 71 22]]


In [ ]:
#Genera un arreglo de 10 números aleatorios entre 0 y 1 y calcula la suma de todos sus elementos.
np.random.rand(10)
print(np.random.rand(10).sum())

5.710683219385892


In [ ]:
#Genera un arreglo de 10 números aleatorios entre 0 y 1 y calcula su media.
np.random.rand(10)
print(np.random.rand(10).mean())

0.51407557134745


# **Tarea Pandas**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#dataframe ficticio de ventas de frutas

df = pd.DataFrame({'Product': ['Carrots', 'Broccoli', 'Banana', 'Banana',

 'Beans', 'Orange', 'Broccoli', 'Banana'],

 'Category': ['Vegetable', 'Vegetable', 'Fruit', 'Fruit',

 'Vegetable', 'Fruit', 'Vegetable', 'Fruit'],

 'Quantity': [8, 5, 3, 4, 5, 9, 11, 8],

 'Amount': [270, 239, 617, 384, 626, 610, 62, 90]})

print(df)

    Product   Category  Quantity  Amount
0   Carrots  Vegetable         8     270
1  Broccoli  Vegetable         5     239
2    Banana      Fruit         3     617
3    Banana      Fruit         4     384
4     Beans  Vegetable         5     626
5    Orange      Fruit         9     610
6  Broccoli  Vegetable        11      62
7    Banana      Fruit         8      90


In [ ]:
#Selecciona e imprime las columnas de Product y Quantity.

print(df[['Product', 'Quantity']])

    Product  Quantity
0   Carrots         8
1  Broccoli         5
2    Banana         3
3    Banana         4
4     Beans         5
5    Orange         9
6  Broccoli        11
7    Banana         8


In [ ]:
#Selecciona e imprime los renglones con índices 4 y 6.
print(df.iloc[[4, 6]])

    Product   Category  Quantity  Amount
4     Beans  Vegetable         5     626
6  Broccoli  Vegetable        11      62


In [ ]:
#Usando el método groupby, agrupa usando la columna Product y muestra la suma de la columna Quantity.
print(df.groupby('Product')['Quantity'].sum())

Product
Banana      15
Beans        5
Broccoli    16
Carrots      8
Orange       9
Name: Quantity, dtype: int64


In [ ]:
#Usando el método groupby, agrupa usando la columna Categoryy muestra la suma de la columna Amount.
print(df.groupby('Category')['Amount'].sum())

Category
Fruit        1701
Vegetable    1197
Name: Amount, dtype: int64
